-- Table 1: Agent specs auto-generated by YANA
CREATE TABLE public.yana_generated_agents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_slug TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  description TEXT NOT NULL,
  agent_type TEXT NOT NULL CHECK (agent_type IN ('sub_agent', 'meta_improvement')),
  system_prompt TEXT NOT NULL,
  allowed_tools TEXT[] NOT NULL DEFAULT '{}',
  schedule TEXT NOT NULL DEFAULT 'on_demand' CHECK (schedule IN ('on_demand', 'hourly', 'daily', 'weekly')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by TEXT NOT NULL DEFAULT 'yana',
  creation_reason TEXT,
  trigger_pattern JSONB DEFAULT '{}'::jsonb,
  execution_count INTEGER NOT NULL DEFAULT 0,
  success_count INTEGER NOT NULL DEFAULT 0,
  last_executed_at TIMESTAMPTZ,
  last_learning TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_yana_generated_agents_active ON public.yana_generated_agents(is_active, schedule);
CREATE INDEX idx_yana_generated_agents_type ON public.yana_generated_agents(agent_type);

ALTER TABLE public.yana_generated_agents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage generated agents"
  ON public.yana_generated_agents FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Authenticated users can view active agents"
  ON public.yana_generated_agents FOR SELECT
  USING (auth.uid() IS NOT NULL AND is_active = true);

CREATE TRIGGER update_yana_generated_agents_updated_at
  BEFORE UPDATE ON public.yana_generated_agents
  FOR EACH ROW EXECUTE FUNCTION public.update_yana_updated_at();

-- Table 2: Execution log for generated agents
CREATE TABLE public.yana_agent_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id UUID NOT NULL REFERENCES public.yana_generated_agents(id) ON DELETE CASCADE,
  user_id UUID,
  trigger_source TEXT NOT NULL DEFAULT 'manual',
  input_summary TEXT,
  output_summary TEXT,
  steps JSONB DEFAULT '[]'::jsonb,
  success BOOLEAN NOT NULL DEFAULT false,
  error_message TEXT,
  duration_ms INTEGER,
  tokens_used INTEGER DEFAULT 0,
  cost_cents INTEGER DEFAULT 0,
  learning_extracted TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_yana_agent_executions_agent ON public.yana_agent_executions(agent_id, created_at DESC);
CREATE INDEX idx_yana_agent_executions_user ON public.yana_agent_executions(user_id, created_at DESC);

ALTER TABLE public.yana_agent_executions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view all executions"
  ON public.yana_agent_executions FOR SELECT
  USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can view their own executions"
  ON public.yana_agent_executions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can insert executions"
  ON public.yana_agent_executions FOR INSERT
  WITH CHECK (true);